version: '2'

services:
  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./dumps:/dumps
  web:
    env_file:
      - .env
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
